---
title: "Pre-course setups and requirements"
toc: false
format: html
---

# About

Here we explain how to install R and RStudio and additional packages on your own computer. This required to ensure a smooth experience and reproducible results during the course.

# Installation

## R

1. Go to the [R website](http://www.r-project.org){target="_blank"}
2. In the column on the left hand side, click on the [CRAN](https://cran.r-project.org/mirrors.html){target="_blank"} link under the subheading **Download**
    - You now see a page with *CRAN Mirrors*. This is a list of servers from which the R software and extensions can be downloaded from
3. Click on the first link
    - Now both the left hand side and the right hand side of the page change (This page can be saved as a bookmark/favorite)
4. On the right hand side, click on the download link for your operating system
    - E.g. Windows users click on [Download R for Windows](https://cloud.r-project.org/){target="_blank"}, then click on base and download the program from there.
    - It is recommended to always install the latest version as well as to update the program if a new major version is released
    - You can use the default installation options


## RStudio Desktop

1. Go to [the download page](https://posit.co/download/rstudio-desktop/){target="_blank"}
2. Scroll down and click on the button for downloading RStudio Desktop
3. Download and install RStudio Desktop
    - You can use the default installation options
4. Open Rstudio Desktop
    - E.g. via the **Start** menu in Windows